# Generated by Django 3.2.7 on 2021-10-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans_scraip', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
