# Generated by Django 3.2.7 on 2021-10-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans_scraip', '0003_special_subweapon_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans_scraip.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='special',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Special',
        ),
        migrations.DeleteModel(
            name='SubWeapon',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
