# Generated by Django 3.2.7 on 2021-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_scraip', '0004_auto_20211005_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='日付')),
                ('shop', models.URLField(verbose_name='店舗名')),
                ('name', models.CharField(max_length=100, verbose_name='スタッフ名')),
                ('departure', models.CharField(max_length=100, verbose_name='出発場所')),
                ('destination', models.CharField(max_length=100, verbose_name='到着場所')),
                ('oneway', models.PositiveIntegerField(verbose_name='片道料金')),
                ('roundway', models.PositiveIntegerField(verbose_name='往復料金')),
                ('sumPrise', models.PositiveIntegerField(verbose_name='合計料金')),
                ('discription', models.TextField(max_length=500, verbose_name='経路詳細')),
            ],
            options={
                'verbose_name': '交通費履歴',
                'verbose_name_plural': '交通費履歴',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
