# Generated by Django 3.2.7 on 2021-10-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_scraip', '0005_auto_20211005_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdata',
            name='fast_low',
            field=models.CharField(max_length=100, null=True, verbose_name='最安/最落'),
        ),
        migrations.AddField(
            model_name='transdata',
            name='tokyu',
            field=models.CharField(max_length=100, null=True, verbose_name='特急'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='date',
            field=models.CharField(max_length=100, null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='departure',
            field=models.CharField(max_length=100, null=True, verbose_name='出発場所'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='destination',
            field=models.CharField(max_length=100, null=True, verbose_name='到着場所'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='discription',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='経路詳細'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='スタッフ名'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='oneway',
            field=models.CharField(max_length=100, null=True, verbose_name='片道料金'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='roundway',
            field=models.CharField(max_length=100, null=True, verbose_name='往復料金'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='shop',
            field=models.CharField(max_length=100, null=True, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='transdata',
            name='sumPrise',
            field=models.CharField(max_length=100, null=True, verbose_name='合計料金'),
        ),
    ]
